[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.136.0"
HUGO_ENV = "production"

[context.production]
command = "hugo --gc --minify --enableGitInfo -b https://yourdomain.com"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next]
command = "hugo --gc --minify --enableGitInfo"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"